# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'курсовая.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(420, 489)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(20, 60, 151, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 160, 151, 21))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 151, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Diametr = QtWidgets.QLabel(self.centralwidget)
        self.Diametr.setGeometry(QtCore.QRect(20, 130, 151, 20))
        self.Diametr.setAlignment(QtCore.Qt.AlignCenter)
        self.Diametr.setObjectName("Diametr")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 290, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(260, 50, 121, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setInputMask("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(189, 50, 61, 141))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.znachB = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.znachB.setAlignment(QtCore.Qt.AlignCenter)
        self.znachB.setObjectName("znachB")
        self.verticalLayout_3.addWidget(self.znachB)
        self.znachH = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.znachH.setAlignment(QtCore.Qt.AlignCenter)
        self.znachH.setObjectName("znachH")
        self.verticalLayout_3.addWidget(self.znachH)
        self.znachN = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.znachN.setAlignment(QtCore.Qt.AlignCenter)
        self.znachN.setObjectName("znachN")
        self.verticalLayout_3.addWidget(self.znachN)
        self.znachl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.znachl.setAlignment(QtCore.Qt.AlignCenter)
        self.znachl.setObjectName("znachl")
        self.verticalLayout_3.addWidget(self.znachl)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 210, 241, 191))
        self.widget.setObjectName("widget")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Сечение опорных конструкций"))
        self.label.setText(_translate("mainWindow", "Класс бетона"))
        self.Diametr.setText(_translate("mainWindow", "Диаметр арматуры"))
        self.pushButton.setText(_translate("mainWindow", "Расчитать"))
        self.znachB.setText(_translate("mainWindow", "b"))
        self.znachH.setText(_translate("mainWindow", "h"))
        self.znachN.setText(_translate("mainWindow", "N"))
        self.znachl.setText(_translate("mainWindow", "l"))
